language: php

env:
  global:
    - DEPENDENCIES=""

matrix:
  include:
    - php: 7.1
      env: DEPENDENCIES="low"
    - php: 7.2
      env: DEPENDENCIES="high"

before_install:
  - composer self-update

install:
  - if [ "$DEPENDENCIES" = "" ]; then composer install --prefer-source; fi
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-source --prefer-lowest; fi
  - if [ "$DEPENDENCIES" = "high" ]; then composer update --prefer-source; fi
